### PR TITLE
Test & fix more parse problems

### PR DESCRIPTION
**Pull request by yomimono**
Performed some additional out-of-band testing with https://github.com/yomimono/somerandompacket until `of_cstruct` didn't find crashes quickly.  Fixes the IPv4 and UDP parse failures in #305 .

### CODE REVIEW

**Comment by talex5** [comment]
Travis failed; we seem to have picked up a dependency on base along the way :-(

```
:(.data+0x87cde8): undefined reference to `Base_internalhash_get_hash_value'
:(.data+0x87cdf0): undefined reference to `Base_internalhash_fold_string'
:(.data+0x87cdf8): undefined reference to `Base_internalhash_fold_float'
:(.data+0x87ce00): undefined reference to `Base_internalhash_fold_int'
:(.data+0x87ce08): undefined reference to `Base_internalhash_fold_int64'
```

**Comment by yomimono** [comment]
Indeed; see https://lists.xenproject.org/archives/html/mirageos-devel/2017-03/msg00036.html for further discussion.  Once https://github.com/ocaml/opam-repository/pull/8794 is merged I'll kick the tests off again.

**Comment by yomimono** [comment]
Passing now & no objections, so I'll merge this.
